# -*- coding: utf-8 -*-
"""DocuSense_–_RAG_Based_Document_Intelligence_System.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zT5y_a0S1kl8OOiGvZ2bk-DGDHUh7Oyw
"""

!pip install striprtf
!pip install PyMuPDF
import fitz
import os
!pip install -U transformers
from google.colab import drive
from striprtf.striprtf import rtf_to_text
drive.mount('/content/drive')
folder_path = "/content/drive/My Drive/article_analysis"
documents = []

for filename in os.listdir(folder_path):
    file_path = os.path.join(folder_path, filename)
    text = ""

    if filename.lower().endswith(".pdf"):
        pdf = fitz.open(file_path)
        for page in pdf:
            text += page.get_text()
        pdf.close()

    elif filename.lower().endswith(".txt"):
        with open(
            file_path,
            "r",
            encoding="utf-8",
            errors="ignore"
        ) as f:
            text = f.read()

    elif filename.lower().endswith(".rtf"):
        with open(
            file_path,
            "r",
            encoding="utf-8",
            errors="ignore"
        ) as f:
            rtf_content = f.read()

        text = rtf_to_text(rtf_content)

    else:
        print(f"Skipping unsupported file: {filename}")
        continue


    documents.append({
        "source": filename,
        "text": text
    })


print(f"\nLoaded {len(documents)} documents")


for doc in documents:
    print(
        doc["source"],
        "->",
        len(doc["text"]),
        "characters"
    )

!pip install langchain langchain-text-splitters
import pandas as pd
from langchain_text_splitters import RecursiveCharacterTextSplitter

# Create articles_df from the documents list generated in a previous cell
articles_df = pd.DataFrame(documents)
articles_df = articles_df.rename(columns={"source": "filename", "text": "article_raw"})

# Initialize the splitter
splitter = RecursiveCharacterTextSplitter(
    chunk_size=1000,
    chunk_overlap=100
)

chunks = []

for _, row in articles_df.iterrows():

    doc_chunks = splitter.split_text(row["article_raw"])

    for i, chunk in enumerate(doc_chunks):
        chunks.append({
            "filename": row["filename"],
            "chunk_id": i,
            "text": chunk
        })

chunks_df = pd.DataFrame(chunks);

print(len(chunks_df))
chunks_df.head()

print(len(documents))

set(articles_df["filename"])

for doc in documents:
    print(doc["source"])

all_chunks = []

for index, row in chunks_df.iterrows():
    all_chunks.append({
        "source": row["filename"],
        "chunk": row["text"]
    })

print("Total Chunks:", len(all_chunks))

import re
from sklearn.feature_extraction.text import ENGLISH_STOP_WORDS


extra_stopwords = set([
    "said","says","also","will","would","could",
    "new","year","news","article","document",
    "date","load","loaded","page",
    "january","february","march","april",
    "may","june","july","august",
    "september","october","november","december",
    "company","companies",
    "2024","2025","2026"
])


stopwords = ENGLISH_STOP_WORDS.union(extra_stopwords)


def clean_text(text):

    text = text.lower()

    text = re.sub(
        r"\d+",
        " ",
        text
    )

    text = re.sub(
        r"[^a-z\s]",
        " ",
        text
    )

    words = text.split()

    words = [
        w for w in words
        if w not in stopwords
        and len(w) > 4
    ]

    return " ".join(words)


# Original text for embeddings (RAG)
embedding_texts = [
    c["chunk"]
    for c in all_chunks
]

# Cleaned text for Topic Modeling (LDA/TF-IDF)
cleaned_texts = [
    clean_text(c["chunk"])
    for c in all_chunks
]

print(cleaned_texts[0][:30000])

from sentence_transformers import SentenceTransformer
import numpy as np

model = SentenceTransformer(
    "all-MiniLM-L6-v2"
)

embeddings = model.encode(
    embedding_texts,
    show_progress_bar=True
)

embeddings = np.array(
    embeddings,
    dtype=np.float32
)

!pip install faiss-cpu
import faiss
import numpy as np

embeddings = np.array(
    embeddings,
    dtype=np.float32
)

dimension = embeddings.shape[1]

index = faiss.IndexFlatL2(
    embeddings.shape[1]
)

index.add(embeddings)

print("Indexed",
      index.ntotal,
      "chunks")

def retrieve(query,
             k=15):

    query_embedding = model.encode(
        [query]
    ).astype(np.float32)

    distances, indices = index.search(
        query_embedding,
        k
    )

    results = []

    for idx in indices[0]:

        results.append(
            all_chunks[idx]
        )

    return results

results = retrieve(
    "What companies are mentioned?"
)

for r in results:

    print("="*80)

    print("SOURCE:",
          r["source"])

    print(r["chunk"][:500])

query = "What companies are mentioned?"

retrieved = retrieve(query)

context = "\n\n".join(
    [x["chunk"] for x in retrieved]
)

prompt = f"""
Context:

{context}

Question:
{query}

Answer only using the context.
"""

!pip install -U openai
import os
os.environ["GROQ_API_KEY"] = "GROQ_API_KEY"
from openai import OpenAI
import os

client = OpenAI(
    api_key=os.environ["GROQ_API_KEY"],
    base_url="https://api.groq.com/openai/v1"
)

response = client.chat.completions.create(
    model="llama-3.3-70b-versatile",
    messages=[
        {
            "role": "user",
            "content": "What is the capital of France?"
        }
    ]
)

print(response.choices[0].message.content)

from openai import OpenAI
import numpy as np
import os

client = OpenAI(
    api_key=os.environ["GROQ_API_KEY"],
    base_url="https://api.groq.com/openai/v1"
)

def retrieve(query, k=30):

    query_embedding = model.encode(
        [query]
    ).astype(np.float32)

    distances, indices = index.search(
        query_embedding,
        k
    )

    results = []

    for idx in indices[0]:
        results.append(all_chunks[idx])

    return results

def ask_rag(question):

    retrieved = retrieve(question, k=30)

    context = "\n\n".join([
        f"""===== ARTICLE =====
Source: {item['source']}

{item['chunk']}
"""
        for item in retrieved
    ])

    print("Context characters:", len(context))

    prompt = f"""
You are answering questions using only the supplied context.

Each context section begins with a source filename.

If the answer comes from multiple articles, mention all relevant source filenames.

If the information is not present in the context, reply:
"Not found in the provided documents."

Context:
{context}

Question:
{question}

Answer:
"""
    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {
                "role":"user",
                "content":prompt
            }
        ],
        temperature=0,
        max_tokens=500
    )

    return response.choices[0].message.content

print("documents" in globals())
print("all_chunks" in globals())

print(type(embeddings))
print(len(embeddings))

print("model" in globals())
print("embeddings" in globals())
print("index" in globals())

def ask_rag_global(question):
    # The original intent was to combine EVERY chunk, but this exceeds token limits.
    # We will now use the retrieve function to get relevant chunks,
    # similar to how ask_rag works, to fit within model constraints.
    retrieved_chunks = retrieve(question, k=50)
     # Using the existing retrieve function
    context = "\n\n".join([
        f"Source: {item['source']}\n{item['chunk']}"
        for item in retrieved_chunks
    ])
    print("Characters (after retrieval):", len(context))

    prompt = f"""
You are answering questions using only the supplied context.

Each context section begins with a source filename.

If the answer comes from multiple articles, mention all relevant source filenames.

If the information is not present in the context, reply:
"Not found in the provided documents."

Context:
{context}

Question:
{question}

Answer:
"""
    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[{"role": "user", "content": prompt}],
        temperature=0,
        max_tokens=500
    )
    return response.choices[0].message.content

print(ask_rag_global("List all companies mentioned in the articles."))

answer=ask_rag("Give the companies in descending order of frequency(i.e. in how many articles, the company is mentioned)")
answer

answer = ask_rag(
    "What is the theme of these articles ?"
)

print(answer)

!pip install gensim
from gensim.corpora import Dictionary
from gensim.utils import simple_preprocess

# Use your chunks from RAG
texts_for_lda = [
    simple_preprocess(text)
    for text in cleaned_texts
]
# Create dictionary
dictionary = Dictionary(texts_for_lda)

# Remove very rare/common words
dictionary.filter_extremes(
    no_below=2,
    no_above=0.8
)

# Create corpus
corpus = [
    dictionary.doc2bow(text)
    for text in texts_for_lda
]

print("Documents:", len(corpus))
print("Vocabulary:", len(dictionary))

from gensim.models import LdaModel, CoherenceModel

scores = []

for k in range(5, 21):

    lda = LdaModel(
        corpus=corpus,
        id2word=dictionary,
        num_topics=k,
        random_state=42,
        passes=10
    )

    cm = CoherenceModel(
        model=lda,
        corpus=corpus,
        dictionary=dictionary,
        coherence="u_mass"
    )

    score = cm.get_coherence()

    scores.append(score)

    print(f"K={k}, Coherence (U_mass)={score:.4f}")

best_k = list(range(5,21))[scores.index(max(scores))]

print("Best K =", best_k)
print("Best score =", max(scores))

retrieved = retrieve(
    "What are the major themes discussed across all articles?",
    k=100
)

context = "\n\n".join(
    [x["chunk"] for x in retrieved]
)

prompt = f"""
Analyze the documents.

Find exactly {best_k} topics.

For each topic provide:
1. Topic Name
2. 10 Keywords

Return as JSON:
[
 {{
   "topic":"...",
   "keywords":[...]
 }}
]
"""

retrieved = retrieve(
    "What are the major themes discussed across all articles?",
    k=20 # Reduced k from 100 to 20 to manage token count
)

context = "\n\n".join(
    [x["chunk"] for x in retrieved]
)

prompt = f"""
You are given news articles.

Use ONLY the information provided in the context.
Do NOT use outside knowledge.

Context:
{context}

Task:
Analyze the documents.

Find exactly {best_k} major topics discussed across all articles.

For each topic provide:
1. Topic Name
2. Exactly 5 representative keywords found in the articles.

Return ONLY valid JSON in this format:

[
  {{
    "topic": "Topic Name",
    "keywords": [
      "keyword1",
      "keyword2",
      "keyword3",
      "keyword4",
      "keyword5"
    ]
  }}
]
"""

topic_output = client.chat.completions.create(
    model="llama-3.3-70b-versatile",
    messages=[
        {
            "role": "user",
            "content": prompt
        }
    ],
    temperature=0,
    max_tokens=1500 # Adjust max_tokens if needed, but 1500 should be sufficient for the JSON output
).choices[0].message.content

print(topic_output)

import json

# Remove markdown if present
clean = topic_output.replace("```json", "").replace("```", "").strip()

topics = json.loads(clean)

import networkx as nx

G = nx.Graph()

for item in topics:
    topic = item["topic"]

    G.add_node(topic)

    for keyword in item["keywords"]:
        G.add_node(keyword)
        G.add_edge(topic, keyword)

import matplotlib.pyplot as plt
import networkx as nx

# Compute node positions
pos = nx.spring_layout(
    G,
    seed=42,
    k=1.5,
    iterations=100
)

# Color map
topic_colors = plt.cm.tab20.colors

node_colors = []

for node in G.nodes():

    color = "lightgray"

    for idx, item in enumerate(topics):
        if node == item["topic"]:
            color = topic_colors[idx % 20]
            break
        elif node in item["keywords"]:
            color = topic_colors[idx % 20]
            break

    node_colors.append(color)

# Node sizes
node_sizes = []

for node in G.nodes():

    if node in [item["topic"] for item in topics]:
        node_sizes.append(3000)   # Topic node
    else:
        node_sizes.append(900)    # Keyword node

# Plot
plt.figure(figsize=(18,12))

nx.draw_networkx_edges(
    G,
    pos,
    alpha=0.4
)

nx.draw_networkx_nodes(
    G,
    pos,
    node_color=node_colors,
    node_size=node_sizes,
    edgecolors="black"
)

nx.draw_networkx_labels(
    G,
    pos,
    font_size=10,
    font_weight="bold"
)

plt.title("Topic-Keyword Network", fontsize=18)
plt.axis("off")
plt.show()